imagenet_train: /mnt/cogsci/ILSVRC2012/training/
imagenet_val: /mnt/cogsci/KhoslaLab/ILSVRC2012/valid
project_path: /home/nirajesh/sparsity_alignment/
device_id: 1
prune_method: amp
metric: pca_dim
prune_all: False
dataset_size: 10000
